// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'Smart Meal Budget App',
  description: 'Plan your meals and budget smarter',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-800 min-h-screen font-sans">
        {/* ✅ Navbar */}
        <nav className="bg-white shadow-md px-6 py-4 flex justify-between items-center">
          <h1 className="text-xl font-bold text-blue-600">🍽️ MealBudget</h1>
          <div className="space-x-6">
            <Link href="/" className="text-gray-700 hover:text-blue-500">Home</Link>
            <Link href="/login" className="text-gray-700 hover:text-blue-500">Login</Link>
            <Link href="/signup" className="text-gray-700 hover:text-blue-500">Sign Up</Link>
          </div>
        </nav>

        {/* ✅ Page Content */}
        <main className="px-6 py-10 max-w-4xl mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}

